### ISSUE TITLE
add statuscode to response

### ISSUE THREAD

**Issue by akshayvijayjain** [sidharthjain-zemoso/NodeJS-Assignments#7]
1. when user already exists, we should throw error with appropriate status code
2. when there is error to be returned return it with appropriate code
3. thus status code should be part of all the response

**Comment by sidharthjain-zemoso** [comment]
![image](https://github.com/sidharthjain-zemoso/NodeJS-Assignments/assets/97596144/06a4cd67-18fe-4d8e-83ec-1f01ed7129ba)

@akshayvijayjain we are throwing error with appropriate code.

**Comment by sidharthjain-zemoso** [comment]
@akshayvijayjain closing this issue.
