### ISSUE TITLE
I feel, you can throw from constructor, if error is already instance of CustomError.

### ISSUE THREAD

**Issue by akshayvijayjain** [sidharthjain-zemoso/NodeJS-Assignments#8]
I feel, you can throw from constructor, if error is already instance of CustomError.

thus we avoid created nested CustomError.

yes, this is what I was referring in my previous comment

_Originally posted by @akshayvijayjain in https://github.com/sidharthjain-zemoso/NodeJS-Assignments/pull/6#discussion_r1604849396_

**Comment by sidharthjain-zemoso** [comment]
Closing this issue as it is fixed @akshayvijayjain
